Add favorite quotes HTML page
ArielSalazar04/my-portfolio-2 pull request #3
Opened 2020-06-13 23:19 UTC by ArielSalazar04

Here I added a "favorite quotes" URL before starting Step 3 of week 2. Although the quotes are hardcoded in the web servlet, I will add them to the datastore when I reach that step.

2020-06-16 20:04 UTC, mickrobk requested changes

2020-06-16 20:04 UTC, mickrobk commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +        String quote = quotes.get((int) (Math.random() * quotes.size()));
While it doesn't much matter here; it is generally not correct to coerce types from random number sources. (See https://stackoverflow.com/questions/738629/math-random-versus-random-nextintint/738651#738651 for example with this exact API)

Most random number libs will offer overrides for each type / usecase / distribution choice. For java, looks like: https://stackoverflow.com/a/363692

2020-06-16 20:04 UTC, mickrobk commented on portfolio/src/main/webapp/favorite-quotes.html
> +    <body onload="getHelloMessage()">
Instead of setting up your js via HTML, can you do it all in JS? (As a starting point, look for "DOMContentLoaded")

2020-06-16 20:04 UTC, mickrobk commented on portfolio/src/main/webapp/favorite-quotes.html
> +                        <p style="font-size:24px;" id="quote-container"></p>
Can you pull this style into your CSS?

2020-06-18 02:50 UTC, ArielSalazar04 commented
The requested changes for this code review have been made. There is an additional commit for adding the project ID to the pom.xml file.

2020-06-18 14:54 UTC, mickrobk approved these changes

2020-06-18 15:33 UTC, merged